### ISSUE TITLE
关于你使用的系统

### ISSUE THREAD

**Issue by dylanochan** [yuchanns/dotfiles#1]
请问截图你使用的系统是什么呢，据我有限的了解是arch + dwm，我觉得很漂亮，如果是的话能否说明一下使用了哪些插件呢？或者在哪可以看到这些资料？

**Comment by yuchanns** [comment]
OS:  Arch Linux
WM: [Hyprland](https://hyprland.org/)
Bar: [Eww](https://elkowar.github.io/eww/)

No external components are utilized. Everything can be located under their respective directory names within the dotfiles.
